# Generated by Django 2.1 on 2020-09-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="designation",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Designation"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="experience",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Experience"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_profile_approved",
            field=models.BooleanField(
                default=False, verbose_name="Profile Verification"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="medical_practice_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Medical practice id",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="shift",
            field=models.IntegerField(
                choices=[(1, "Morning"), (2, "Afternoon"), (3, "Evening")],
                default=1,
                verbose_name="Shift",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="speciality",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="speciality"
            ),
        ),
    ]
