# Generated by Django 2.1 on 2020-09-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_role",
            field=models.IntegerField(
                choices=[
                    (1, "Admin"),
                    (2, "Subadmin"),
                    (3, "Patient"),
                    (4, "Doctor"),
                    (5, "Manager"),
                    (6, "Insurance_verifier"),
                    (7, "Clerical_staff"),
                ],
                default=3,
                verbose_name="User role",
            ),
        ),
    ]
