# Generated by Django 2.1 on 2020-10-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200929_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp_type',
            field=models.IntegerField(choices=[(1, 'Email Verification'), (2, 'Forgot Password'), (3, 'Update Profile'), (4, 'Doc Verification')], default=1, verbose_name='OTP type'),
        ),
    ]
