# Generated by Django 2.1 on 2020-10-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201001_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.IntegerField(choices=[(1, 'MD'), (2, 'DO'), (3, 'PA'), (4, 'NP')], default=1, verbose_name='Designation'),
        ),
    ]
