# Generated by Django 2.1 on 2020-10-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201012_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.IntegerField(choices=[(1, 'Physician'), (2, 'PA'), (3, 'NP')], default=1, verbose_name='Designation'),
        ),
    ]
