# Generated by Django 2.1 on 2020-10-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201013_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_type',
            field=models.IntegerField(choices=[(1, 'Email Verification'), (2, 'Forgot Password'), (3, 'Update Profile'), (4, 'Doc Verification'), (5, 'Login Otp')], default=1, verbose_name='OTP type'),
        ),
    ]
