# Generated by Django 2.1 on 2020-11-19 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Van',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('van_number', models.CharField(blank=True, max_length=70, null=True, verbose_name='Van Number')),
                ('level_type', models.IntegerField(choices=[(1, 'Level1'), (2, 'Level2')], default=1, verbose_name='Van level type')),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_vans', to='accounts.Hub')),
            ],
            options={
                'verbose_name': 'BaseModel',
                'abstract': False,
            },
        ),
    ]
