# Generated by Django 2.1 on 2020-11-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_van'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lat',
            field=models.DecimalField(decimal_places=50, default=0.0, max_digits=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='lng',
            field=models.DecimalField(decimal_places=50, default=0.0, max_digits=200),
        ),
    ]
