# Generated by Django 2.1 on 2020-12-02 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201120_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('tick_name', models.TextField(max_length=200)),
                ('email_add', models.EmailField(max_length=70, unique=True, verbose_name='Email Address')),
                ('ticket_regard', models.BooleanField(blank=True, default=False, null=True)),
                ('ticket_regard_type', models.IntegerField(choices=[(1, 'room not available'), (2, 'van not available'), (3, 'change time'), (4, 'change date'), (5, 'others')], default=1, verbose_name='Ticet Regard type')),
                ('add_note', models.TextField(max_length=200)),
                ('is_resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tickettable',
            },
        ),
    ]
