# Generated by Django 2.1 on 2020-12-10 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

created_at_variable = 'Created At'
updated_at_variable = 'Last Updated At'

class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('accounts', '0012_auto_20201120_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=created_at_variable)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=updated_at_variable)),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('phone_number', models.CharField(blank=True, max_length=19, null=True, unique=True, verbose_name='Phone Number')),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_emergency_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BaseModel',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=created_at_variable)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=updated_at_variable)),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('dob', models.DateField(blank=True, null=True)),
                ('relation', models.CharField(blank=True, max_length=120, null=True, verbose_name='Relation')),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_family_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BaseModel',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsuranceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=created_at_variable)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=updated_at_variable)),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('groupid', models.CharField(max_length=50, verbose_name='Group Id')),
                ('policyid', models.CharField(max_length=50, verbose_name='Policy Id')),
                ('securitynumber', models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Social Security Number')),
                ('is_deleted', models.BooleanField(default=False)),
                ('profile_image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.AllImage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_insurance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BaseModel',
                'abstract': False,
            },
        ),
    ]
