# Generated by Django 2.1 on 2020-12-02 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'BaseModel'},
        ),
        migrations.AlterModelTable(
            name='ticket',
            table=None,
        ),
    ]
