# Generated by Django 2.1 on 2020-12-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20201202_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
