# Generated by Django 2.1 on 2020-12-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_ticket_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_regard',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='email_add',
            field=models.EmailField(max_length=70, verbose_name='Email Address'),
        ),
    ]
