# Generated by Django 2.1 on 2020-12-14 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_emergencycontacts_familymember_insurancedetails'),
        ('accounts', '0017_virtualroom'),
    ]

    operations = [
    ]
