# Generated by Django 2.1 on 2020-12-14 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_merge_20201214_0459'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('is_diabetes', models.BooleanField(default=False, verbose_name='Diabetes')),
                ('is_chest_pain', models.BooleanField(default=False, verbose_name='Chest Pain')),
                ('is_Angina', models.BooleanField(default=False, verbose_name='Angina')),
                ('is_high_blood_pressure', models.BooleanField(default=False, verbose_name='High Blood Pressure')),
                ('is_heart_disease', models.BooleanField(default=False, verbose_name='Heart Disease')),
                ('is_heart_attack', models.BooleanField(default=False, verbose_name='Heart Attack')),
                ('is_heart_paipitations', models.BooleanField(default=False, verbose_name='Heart Paipitations')),
                ('is_pacemaker', models.BooleanField(default=False, verbose_name='Pacemaker')),
                ('is_headaches', models.BooleanField(default=False, verbose_name='Headaches')),
                ('is_kidney_problem', models.BooleanField(default=False, verbose_name='Kidney Problems')),
                ('is_are_you_pregnant', models.BooleanField(default=False, verbose_name='Are You Pregnant?')),
                ('is_cancer', models.BooleanField(default=False, verbose_name='Cancer')),
                ('is_osteoporosis', models.BooleanField(default=False, verbose_name='Osteoporosis')),
                ('is_bladder_abnormalities', models.BooleanField(default=False, verbose_name='Bladder Abnormalities ')),
                ('is_asthma', models.BooleanField(default=False, verbose_name='Asthma')),
                ('is_breathing_difficulties', models.BooleanField(default=False, verbose_name='Breathing Difficulties')),
                ('is_liver', models.BooleanField(default=False, verbose_name='Liver')),
                ('is_gallbladder_problems', models.BooleanField(default=False, verbose_name='Gallbladder Problems')),
                ('is_smoking', models.BooleanField(default=False, verbose_name='Smoking')),
                ('is_stroke', models.BooleanField(default=False, verbose_name='Stroke/CVA')),
                ('is_allergies', models.BooleanField(default=False, verbose_name='Allergies')),
                ('is_seizures', models.BooleanField(default=False, verbose_name='Seizures')),
                ('is_metal_implants', models.BooleanField(default=False, verbose_name='Metal Implants')),
                ('is_dizziness', models.BooleanField(default=False, verbose_name='Dizzines/Fainting')),
                ('is_recent_fractures', models.BooleanField(default=False, verbose_name='Recent Fractures')),
                ('is_surgeries', models.BooleanField(default=False, verbose_name='Surgeries')),
                ('specialrequest', models.CharField(blank=True, max_length=120, null=True, verbose_name='Special Request')),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_medical_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BaseModel',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='virtualroom',
            name='room_number',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Room Number'),
        ),
    ]
