# Generated by Django 2.1 on 2020-12-16 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20201216_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingdocandapp',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
