# Generated by Django 2.1 on 2020-12-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20201216_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingdocandapp',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
    ]
