# Generated by Django 2.1 on 2020-12-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20201216_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingdocandapp',
            name='rating_doc_or_app',
            field=models.IntegerField(choices=[(1, 'rating_doc'), (2, 'rating_app')], default=1, verbose_name='rating_doc_or_app'),
        ),
    ]
