# Generated by Django 2.1 on 2020-12-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20201216_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancedetails',
            name='securitynumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='Social Security Number'),
        ),
    ]
