# Generated by Django 2.1 on 2020-12-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20201216_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubdocs',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
