# Generated by Django 2.1 on 2020-12-21 08:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_hubdocs_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_medical_practice_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
