# Generated by Django 2.1 on 2020-12-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_user_admin_medical_practice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualroom',
            name='room_number',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Room Number'),
        ),
    ]
