# Generated by Django 2.1 on 2020-12-23 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('accounts', '0030_auto_20201221_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('cm_email', models.EmailField(max_length=70, verbose_name='Email')),
                ('cm_phone_number', models.CharField(blank=True, max_length=19, null=True, verbose_name='Phone Number')),
                ('is_deleted_terms_condition_pdf', models.BooleanField(default=False)),
                ('is_deleted_legal_terms_pdf', models.BooleanField(default=False)),
                ('cm_legal_terms_pdf', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cm_legal_terms_pdf', to='images.AllImage')),
                ('cm_terms_condition_pdf', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cm_terms_condition_pdf', to='images.AllImage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_content_management', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BaseModel',
                'abstract': False,
            },
        ),
    ]
