# Generated by Django 2.1 on 2020-12-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_contentmanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontacts',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='Phone Number'),
        ),
    ]
