# Generated by Django 2.1 on 2020-12-28 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20201228_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='familymember',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_member_medical_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='is_hernia',
            field=models.BooleanField(default=False, verbose_name='Hernia'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='is_hypoglycemia',
            field=models.BooleanField(default=False, verbose_name='Hypoglycemia'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='is_urine_leakage',
            field=models.BooleanField(default=False, verbose_name='Urine Leakage'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='is_vomiting',
            field=models.BooleanField(default=False, verbose_name='Vomit'),
        ),
    ]
