# Generated by Django 2.1 on 2020-12-28 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20201228_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='familymember',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_member_medical_history', to='accounts.FamilyMember'),
        ),
    ]
