# Generated by Django 2.1 on 2020-12-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20201228_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='is_bladder_abnormalities',
            new_name='is_bowel_bladder_abnormalities',
        ),
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='is_chest_pain',
            new_name='is_chest_pain_angina',
        ),
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='is_dizziness',
            new_name='is_dizziness_fainting',
        ),
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='is_gallbladder_problems',
            new_name='is_liver_gallbladder_problems',
        ),
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='is_stroke',
            new_name='is_stroke_cva',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='is_Angina',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='is_hernia',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='is_hypoglycemia',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='is_urine_leakage',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='is_vomiting',
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='is_arthritis',
            field=models.BooleanField(default=False, verbose_name='Aarthritis'),
        ),
    ]
