# Generated by Django 2.1 on 2021-01-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20201231_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontacts',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Phone Number'),
        ),
    ]
