# Generated by Django 2.1 on 2021-01-06 14:02

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20210106_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('booking_for', models.IntegerField(choices=[(1, 'patient'), (2, 'familymember')], default=1, verbose_name='BookingFor')),
                ('visit_type', models.IntegerField(choices=[(1, 'mobile_doc'), (2, 'video_confer'), (3, 'hub_visit')], default=3, verbose_name='Visit Type')),
                ('source_address', models.CharField(blank=True, max_length=600, null=True, verbose_name='Source Address')),
                ('source_lat', models.DecimalField(decimal_places=50, default=0.0, max_digits=200)),
                ('source_lng', models.DecimalField(decimal_places=50, default=0.0, max_digits=200)),
                ('source_cordinate', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Source Cordinate')),
                ('destination_address', models.CharField(blank=True, max_length=600, null=True, verbose_name='Destination Address')),
                ('destination_lat', models.DecimalField(decimal_places=50, default=0.0, max_digits=200)),
                ('destination_lng', models.DecimalField(decimal_places=50, default=0.0, max_digits=200)),
                ('destination_cordinate', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Destination Cordinate')),
                ('visit_start_time', models.DateField(blank=True, null=True)),
                ('visit_end_time', models.DateField(blank=True, null=True)),
                ('visit_time', models.DateField(blank=True, null=True)),
                ('has_medical_history', models.BooleanField(default=False, verbose_name='Has Medical History')),
                ('has_insurance', models.BooleanField(default=False, verbose_name='Has Insurance')),
                ('total_distance', models.DecimalField(decimal_places=50, default=0.0, max_digits=200)),
                ('total_amount', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('co_pay', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_doctor', to=settings.AUTH_USER_MODEL)),
                ('familymember_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_familymember', to='accounts.FamilyMember')),
                ('hub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_hub', to='accounts.Hub')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_patient', to=settings.AUTH_USER_MODEL)),
                ('ratingdocapp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_ratingdocapp', to='accounts.RatingDocAndApp')),
                ('room_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_room', to='accounts.Room')),
                ('va_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_van', to='accounts.Van')),
                ('virtualroom_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_virtualroom', to='accounts.VirtualRoom')),
            ],
            options={
                'verbose_name': 'BaseModel',
                'abstract': False,
            },
        ),
    ]
