# Generated by Django 2.1 on 2021-01-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='familymember_id',
            new_name='familymember',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='hub_id',
            new_name='hub',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='ratingdocapp_id',
            new_name='ratingdocapp',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='room_id',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='va_id',
            new_name='van',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='virtualroom_id',
            new_name='virtualroom',
        ),
    ]
