# Generated by Django 2.1 on 2021-01-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20210106_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='visit_now_later',
            field=models.IntegerField(choices=[(1, 'visit_now'), (2, 'visit_later')], default=1, verbose_name='Visit Time'),
        ),
    ]
