# Generated by Django 2.1 on 2021-01-07 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20210107_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='ratingdocapp',
        ),
        migrations.AddField(
            model_name='booking',
            name='ratingapp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_ratingapp', to='accounts.RatingDocAndApp'),
        ),
        migrations.AddField(
            model_name='booking',
            name='ratingdoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_ratingdoc', to='accounts.RatingDocAndApp'),
        ),
    ]
