# Generated by Django 2.1 on 2021-01-14 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('accounts', '0043_devicemanagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempDoctorMedicalDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'BaseModel',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TempDoctorWorkInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('designation', models.IntegerField(choices=[(1, 'Physician'), (2, 'PA'), (3, 'NP')], default=1, verbose_name='Designation')),
                ('medical_practice_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Medical practice id')),
                ('speciality', models.CharField(blank=True, max_length=100, null=True, verbose_name='speciality')),
                ('experience', models.FloatField(blank=True, default=0, null=True, verbose_name='Experience')),
                ('shift', models.IntegerField(choices=[(1, 'Morning'), (2, 'Afternoon'), (3, 'Evening')], default=1, verbose_name='Shift')),
                ('is_profile_approved', models.BooleanField(default=False, verbose_name='Profile Verification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tempdoctorworkinfo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BaseModel',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tempdoctormedicaldoc',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_doctormedicaldoc', to='accounts.TempDoctorWorkInfo'),
        ),
        migrations.AddField(
            model_name='tempdoctormedicaldoc',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='images.AllImage'),
        ),
    ]
