# Generated by Django 2.1 on 2021-01-14 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_auto_20210114_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempdoctormedicaldoc',
            old_name='doctor',
            new_name='tempdoctor',
        ),
    ]
