# Generated by Django 2.1 on 2021-01-14 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_tempdoctormedicaldoc_tempdoctorinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempdoctormedicaldoc',
            name='tempdoctorinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tempdoctorinfo_documents', to='accounts.TempDoctorWorkInfo'),
        ),
    ]
