# Generated by Django 2.1 on 2021-01-14 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_auto_20210114_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempdoctormedicaldoc',
            name='tempdoctor',
        ),
    ]
