# Generated by Django 2.1 on 2021-01-14 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_remove_tempdoctormedicaldoc_tempdoctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempdoctormedicaldoc',
            name='tempdoctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tempdoctormedicaldoc', to=settings.AUTH_USER_MODEL),
        ),
    ]
