# Generated by Django 2.1 on 2021-01-14 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_tempdoctormedicaldoc_tempdoctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempdoctormedicaldoc',
            name='tempdoctorinfo',
        ),
    ]
