# Generated by Django 2.1 on 2021-01-14 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_tempdoctormedicaldoc_tempdoctorinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempdoctormedicaldoc',
            name='tempdoctor',
        ),
    ]
