# Generated by Django 2.1 on 2021-01-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_auto_20210115_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempdoctorworkinfo',
            name='is_profile_approved',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Profile Verification'),
        ),
        migrations.AlterField(
            model_name='tempdoctorworkinfo',
            name='shift',
            field=models.IntegerField(blank=True, choices=[(1, 'Morning'), (2, 'Afternoon'), (3, 'Evening')], default=1, null=True, verbose_name='Shift'),
        ),
    ]
