# Generated by Django 2.1 on 2021-01-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_auto_20210115_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempdoctorworkinfo',
            name='experience',
            field=models.FloatField(blank=True, null=True, verbose_name='Experience'),
        ),
    ]
