# Generated by Django 2.1 on 2021-01-19 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_insurance', to='accounts.InsuranceDetails'),
        ),
        migrations.AddField(
            model_name='booking',
            name='medicalhistory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_medicalhistory', to='accounts.MedicalHistory'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='isread'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='message',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='message'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='payload',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='payload'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='title'),
        ),
    ]
