# Generated by Django 2.1 on 2021-01-20 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_auto_20210119_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('skin', models.IntegerField(blank=True, choices=[(1, 'rash'), (2, 'allergy'), (3, 'itching')], default=None, null=True, verbose_name='Skin')),
                ('general', models.IntegerField(blank=True, choices=[(1, 'fever'), (2, 'body_aches')], default=None, null=True, verbose_name='General')),
                ('eye', models.IntegerField(blank=True, choices=[(1, 'pain'), (2, 'redness'), (3, 'itching'), (4, 'blurryvision')], default=None, null=True, verbose_name='Eye')),
                ('ear_nose_throat', models.IntegerField(blank=True, choices=[(1, 'ear_pain'), (2, 'foreign_body'), (3, 'sore_throat'), (4, 'nasal_congestion'), (5, 'sinus_pain')], default=None, null=True, verbose_name='Ear_Nose_Throat')),
                ('chest', models.IntegerField(blank=True, choices=[(1, 'cough'), (2, 'chest_pain'), (3, 'palpitation'), (4, 'difficulty_breathing')], default=None, null=True, verbose_name='Chest')),
                ('abdomen', models.IntegerField(blank=True, choices=[(1, 'nausea'), (2, 'vomitting'), (3, 'diarrhea'), (4, 'abdominal_pain'), (5, 'constipation'), (6, 'rectal_bleeding')], default=None, null=True, verbose_name='Abdomen')),
                ('urinary', models.IntegerField(blank=True, choices=[(1, 'burning_pain'), (2, 'blood')], default=None, null=True, verbose_name='Urinary')),
                ('female', models.IntegerField(blank=True, choices=[(1, 'vaginal bleeding'), (2, 'others')], default=None, null=True, verbose_name='Female')),
                ('generalbody', models.IntegerField(blank=True, choices=[(1, 'backaches'), (2, 'musclepain'), (3, 'jointpain')], default=None, null=True, verbose_name='General_Body')),
                ('neurological_brain', models.IntegerField(blank=True, choices=[(1, 'headache'), (2, 'dizziness'), (3, 'passedout'), (4, 'change in speech'), (5, 'one side weak')], default=None, null=True, verbose_name='Neurological_Brain')),
                ('diabetes', models.IntegerField(blank=True, choices=[(1, 'abnormal body sugar'), (2, 'very thirsty'), (3, 'urinating frequently')], default=None, null=True, verbose_name='Diabetes')),
                ('mental_health', models.IntegerField(blank=True, choices=[(1, 'anxiety'), (2, 'depression'), (3, 'suicidal thought')], default=None, null=True, verbose_name='Mental_Health')),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms_booking', to='accounts.Booking')),
            ],
            options={
                'verbose_name': 'BaseModel',
                'abstract': False,
            },
        ),
    ]
