# Generated by Django 2.1 on 2021-01-20 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptoms',
            name='booking_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symptoms_booking', to='accounts.Booking'),
        ),
    ]
