# Generated by Django 2.1 on 2021-01-21 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_auto_20210120_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistoryItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicalhistory_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='medicalhistory_name')),
            ],
        ),
        migrations.CreateModel(
            name='SymptomsItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='symptoms_name')),
            ],
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='medicalhistory_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_medical_history', to='accounts.MedicalHistoryItems'),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='symptoms_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_symptoms', to='accounts.SymptomsItems'),
        ),
    ]
