# Generated by Django 2.1 on 2021-01-21 09:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_auto_20210121_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistoryitems',
            name='medicalhistory_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='symptomsitems',
            name='symptoms_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
