# Generated by Django 2.1 on 2021-01-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_auto_20210121_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='is_allergies',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='is_are_you_pregnant',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='is_arthritis',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='is_asthma',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='is_bowel_bladder_abnormalities',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='is_breathing_difficulties',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='is_cancer',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='is_chest_pain_angina',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='is_diabetes',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='is_dizziness_fainting',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='is_headaches',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='is_heart_attack',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='is_heart_disease',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='is_heart_paipitations',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='is_high_blood_pressure',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='is_kidney_problem',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='is_liver',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='is_liver_gallbladder_problems',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='is_metal_implants',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='is_osteoporosis',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='is_pacemaker',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='is_recent_fractures',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='is_seizures',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='is_smoking',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='is_stroke_cva',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='is_surgeries',
        ),
    ]
