# Generated by Django 2.1 on 2021-01-21 14:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_auto_20210121_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='medicalhistory_item_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
