# Generated by Django 2.1 on 2021-01-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_medicalhistory_medicalhistory_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistoryitems',
            name='medicalhistory_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='medicalhistory_name'),
        ),
        migrations.AlterField(
            model_name='symptomsitems',
            name='symptoms_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='symptoms_name'),
        ),
    ]
