# Generated by Django 2.1 on 2021-01-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_auto_20210121_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='medicalhistory_item_ids',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.MedicalHistoryItems'),
        ),
    ]
