# Generated by Django 2.1 on 2021-01-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_medicalhistory_medicalhistory_item_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='medicalhistory_item_ids',
            field=models.ManyToManyField(blank=True, null=True, related_name='medicalhist_items', to='accounts.MedicalHistoryItems'),
        ),
    ]
