# Generated by Django 2.1 on 2021-01-21 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_auto_20210121_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='medicalhistory_item_ids',
        ),
    ]
