# Generated by Django 2.1 on 2021-01-22 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0072_remove_medicalhistory_medicalhistory_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='medicalitems',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicalitems_documents', to='accounts.MedicalHistoryItems'),
        ),
    ]
