# Generated by Django 2.1 on 2021-01-22 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0073_medicalhistory_medicalitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='medicalitems',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicalitems_id', to='accounts.MedicalHistoryItems'),
        ),
    ]
