# Generated by Django 2.1 on 2021-01-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0074_auto_20210122_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='medicalitems',
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='items',
            field=models.ManyToManyField(to='accounts.MedicalHistoryItems'),
        ),
    ]
