# Generated by Django 2.1 on 2021-01-23 10:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0075_auto_20210122_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='medhis_item_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
