# Generated by Django 2.1 on 2021-01-23 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0076_medicalhistory_medhis_item_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='medhis_item_ids',
        ),
    ]
