# Generated by Django 2.1 on 2021-01-23 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0077_remove_medicalhistory_medhis_item_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicemanagement',
            name='device_description',
        ),
    ]
