# Generated by Django 2.1 on 2021-01-23 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0078_remove_devicemanagement_device_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemanagement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_device', to=settings.AUTH_USER_MODEL),
        ),
    ]
