# Generated by Django 2.1 on 2021-01-24 19:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0079_auto_20210123_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptoms',
            name='abdomen',
        ),
        migrations.RemoveField(
            model_name='symptoms',
            name='chest',
        ),
        migrations.RemoveField(
            model_name='symptoms',
            name='diabetes',
        ),
        migrations.RemoveField(
            model_name='symptoms',
            name='ear_nose_throat',
        ),
        migrations.RemoveField(
            model_name='symptoms',
            name='eye',
        ),
        migrations.RemoveField(
            model_name='symptoms',
            name='female',
        ),
        migrations.RemoveField(
            model_name='symptoms',
            name='general',
        ),
        migrations.RemoveField(
            model_name='symptoms',
            name='generalbody',
        ),
        migrations.RemoveField(
            model_name='symptoms',
            name='mental_health',
        ),
        migrations.RemoveField(
            model_name='symptoms',
            name='neurological_brain',
        ),
        migrations.RemoveField(
            model_name='symptoms',
            name='skin',
        ),
        migrations.RemoveField(
            model_name='symptoms',
            name='urinary',
        ),
        migrations.RemoveField(
            model_name='symptomsitems',
            name='symptoms_name',
        ),
        migrations.AddField(
            model_name='symptoms',
            name='items',
            field=models.ManyToManyField(to='accounts.SymptomsItems'),
        ),
        migrations.AddField(
            model_name='symptomsitems',
            name='Category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='symptomsitems',
            name='SubCategory',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None),
        ),
    ]
