# Generated by Django 2.1 on 2021-01-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0080_auto_20210124_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symptomsitems',
            old_name='Category',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='symptomsitems',
            name='SubCategory',
        ),
        migrations.AddField(
            model_name='symptomsitems',
            name='subcategory',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SubCategory'),
        ),
    ]
