# Generated by Django 2.1 on 2021-01-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0081_auto_20210124_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='visit_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='visit_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='visit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
