# Generated by Django 2.1 on 2021-01-27 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0082_auto_20210127_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAssignDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('visit_type', models.IntegerField(choices=[(1, 'Mobile Doctor'), (2, 'Video Conferencing'), (3, 'Hub Visit')], default=3, verbose_name='Visit Type')),
                ('shift', models.IntegerField(choices=[(1, 'Morning'), (2, 'Afternoon'), (3, 'Evening')], default=1, verbose_name='Shift')),
                ('date', models.DateField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_doctorassign', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BaseModel',
                'abstract': False,
            },
        ),
    ]
