# Generated by Django 2.1 on 2021-01-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0083_doctorassigndaily'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='state',
            field=models.IntegerField(choices=[(1, 'new'), (2, 'cancel'), (3, 'completed'), (4, 'paid')], default=1, verbose_name='State'),
        ),
    ]
