# Generated by Django 2.1 on 2021-01-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0084_booking_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='items',
            field=models.ManyToManyField(blank=True, to='accounts.MedicalHistoryItems'),
        ),
    ]
