# Generated by Django 2.1 on 2021-01-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0085_auto_20210128_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptoms',
            name='items',
            field=models.ManyToManyField(blank=True, to='accounts.SymptomsItems'),
        ),
    ]
