# Generated by Django 2.1 on 2021-02-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0086_auto_20210129_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancedetails',
            name='securitynumber',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Social Security Number'),
        ),
    ]
