# Generated by Django 2.1 on 2021-02-05 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0087_auto_20210202_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancedetails',
            name='familymember',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_familymember', to='accounts.FamilyMember'),
        ),
    ]
