# Generated by Django 2.1 on 2021-02-08 04:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0088_insurancedetails_familymember'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='medical_disclosure',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.IntegerField(choices=[(1, 'Admin sent you a notification'), (2, 'Sent Admin noyi for insurance')], verbose_name='Activity Type'),
        ),
    ]
