# Generated by Django 2.1 on 2021-02-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0090_auto_20210208_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorassigndaily',
            name='shift',
            field=models.IntegerField(blank=True, choices=[(1, 'Morning'), (2, 'Afternoon'), (3, 'Evening')], null=True, verbose_name='Shift'),
        ),
        migrations.AlterField(
            model_name='doctorassigndaily',
            name='visit_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Mobile Doctor'), (2, 'Video Conferencing'), (3, 'Hub Visit')], null=True, verbose_name='Visit Type'),
        ),
    ]
