# Generated by Django 2.1 on 2021-02-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0091_auto_20210208_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_for',
            field=models.IntegerField(blank=True, choices=[(1, 'patient'), (2, 'familymember')], null=True, verbose_name='BookingFor'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='state',
            field=models.IntegerField(choices=[(1, 'new'), (3, 'booking_created'), (2, 'cancel'), (4, 'completed'), (5, 'paid')], default=1, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='visit_now_later',
            field=models.IntegerField(blank=True, choices=[(1, 'visit_now'), (2, 'visit_later')], null=True, verbose_name='Visit Time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='visit_type',
            field=models.IntegerField(blank=True, choices=[(1, 'mobile_doc'), (2, 'video_confer'), (3, 'hub_visit')], null=True, verbose_name='Visit Type'),
        ),
    ]
