# Generated by Django 2.1 on 2021-02-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0092_auto_20210209_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorassigndaily',
            name='shift_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorassigndaily',
            name='shift_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
