# Generated by Django 2.1 on 2021-02-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0094_auto_20210210_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorassigndaily',
            name='shift_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorassigndaily',
            name='shift_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
