# Generated by Django 2.1 on 2021-02-10 19:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0096_remove_booking_medical_disclosure'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='medical_disclosure',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
