# Generated by Django 2.1 on 2021-02-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0098_booking_meet_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amnt_percent_deduct',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
