# Generated by Django 2.1 on 2021-02-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0099_booking_amnt_percent_deduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_cancel_charge',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True),
        ),
    ]
