# Generated by Django 2.1 on 2021-02-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0100_booking_booking_cancel_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
    ]
