# Generated by Django 2.1 on 2021-02-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0101_hub_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='co_pay',
            field=models.FloatField(blank=True, null=True, verbose_name='co pay'),
        ),
    ]
