# Generated by Django 2.1 on 2021-02-24 11:20

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0103_auto_20210222_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolesManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('modules', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'onboarding'), (2, 'dashboard'), (3, 'user management'), (4, 'staff user management'), (5, 'visit management'), (6, 'hub management'), (7, 'content management'), (8, 'document management'), (9, 'payment management'), (10, 'trouble tickets')], max_length=20, null=True, verbose_name='Modules assignment')),
                ('user_role', models.CharField(blank=True, max_length=30, null=True, verbose_name='User role')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
            ],
            options={
                'verbose_name': 'BaseModel',
                'abstract': False,
            },
        ),
    ]
