# Generated by Django 2.1 on 2021-03-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0106_auto_20210224_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Subadmin'), (3, 'Patient'), (4, 'Doctor')], default=3, verbose_name='User role'),
        ),
    ]
