# Generated by Django 2.1 on 2021-03-08 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0109_auto_20210308_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='visit_time',
        ),
    ]
