# Generated by Django 2.1 on 2021-03-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0110_remove_booking_visit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontacts',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Phone_Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='PhoneNumber'),
        ),
    ]
