# Generated by Django 2.1 on 2021-03-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0111_auto_20210308_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptoms',
            name='additional_info',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='additinal info'),
        ),
    ]
