# Generated by Django 2.1 on 2021-03-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0112_symptoms_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingdocandapp',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
