# Generated by Django 2.1 on 2021-03-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0114_auto_20210316_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='card_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='card id'),
        ),
    ]
