# Generated by Django 2.1 on 2021-03-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0115_booking_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_bank_account',
            field=models.BooleanField(default=False, verbose_name='Has bank account'),
        ),
    ]
