# Generated by Django 2.1 on 2021-03-26 06:41

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0116_user_has_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolesmanagement',
            name='modules_access',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'onboarding'), (2, 'dashboard'), (3, 'user management'), (4, 'staff user management'), (5, 'visit management'), (6, 'hub management'), (7, 'content management'), (8, 'document management'), (9, 'payment management'), (10, 'trouble tickets'), (11, 'shift management')], max_length=23, null=True, verbose_name='Modules assignment'),
        ),
    ]
