# Generated by Django 2.1 on 2021-03-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0118_designation_amount_paymentmanagementadmin_totalamountpaidtodoctormonthly'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation_amount',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is deleted'),
        ),
    ]
