# Generated by Django 2.1 on 2021-03-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0119_designation_amount_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmanagementadmin',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='paymentmanagementadmin',
            name='workinghours',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
