# Generated by Django 2.1 on 2021-03-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0120_auto_20210331_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation_amount',
            name='designation_amount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='designation_amount'),
        ),
    ]
