# Generated by Django 2.1 on 2021-03-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0121_auto_20210331_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalamountpaidtodoctormonthly',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year'),
        ),
    ]
