# Generated by Django 2.1 on 2021-04-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0122_totalamountpaidtodoctormonthly_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentManagementAdmin',
            new_name='DoctorPerDayAmount',
        ),
        migrations.DeleteModel(
            name='TotalAmountPaidToDoctorMonthly',
        ),
        migrations.RemoveField(
            model_name='designation_amount',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='doctorassigndaily',
            name='workinghours',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
