# Generated by Django 2.1 on 2021-04-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0123_auto_20210402_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorperdayamount',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='ispaid'),
        ),
    ]
