# Generated by Django 2.1 on 2021-04-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0124_doctorperdayamount_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicShiftManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('shift_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='shift_name')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is_deleted')),
            ],
            options={
                'verbose_name': 'BaseModel',
                'abstract': False,
            },
        ),
    ]
