# Generated by Django 2.1 on 2021-04-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0125_dynamicshiftmanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancedetails',
            name='insurance_state',
            field=models.IntegerField(choices=[(1, 'create insurance'), (2, 'new'), (3, 'verifying'), (4, 'approve'), (5, 'disapprove')], default=1, verbose_name='Insurance State'),
        ),
    ]
