# Generated by Django 2.1 on 2021-04-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0126_insurancedetails_insurance_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancedetails',
            name='verification_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
