# Generated by Django 2.1 on 2021-04-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0127_insurancedetails_verification_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='payload',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='payload'),
        ),
    ]
