# Generated by Django 2.1 on 2021-04-15 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0128_auto_20210415_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancedetails',
            name='verification_date',
        ),
    ]
