# Generated by Django 2.1 on 2021-04-15 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0129_remove_insurancedetails_verification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancedetails',
            name='handled_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='insurancedetails',
            name='hold_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='insurancedetails',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
