# Generated by Django 2.1 on 2021-04-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0130_auto_20210415_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status_doctor',
            field=models.IntegerField(choices=[(1, 'new'), (2, 'update'), (3, 'approve'), (4, 'disapprove')], default=1, verbose_name='state'),
        ),
    ]
