# Generated by Django 2.1 on 2021-04-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0131_user_status_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancedetails',
            name='insurance_state',
            field=models.IntegerField(choices=[(1, 'create insurance'), (2, 'new'), (3, 'verifying'), (4, 'approve'), (5, 'disapprove'), (6, 'hide')], default=1, verbose_name='Insurance State'),
        ),
    ]
