# Generated by Django 2.1 on 2021-04-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0132_auto_20210418_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='card id'),
        ),
    ]
