# Generated by Django 2.1 on 2021-04-20 19:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0134_doctordailyavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('insurance_state', models.IntegerField(choices=[(1, 'create insurance'), (2, 'new'), (3, 'verifying'), (4, 'approve'), (5, 'disapprove'), (6, 'hide')], default=1, verbose_name='Insurance State')),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('hold_time', models.DurationField(default=datetime.timedelta(0))),
                ('handled_time', models.DurationField(default=datetime.timedelta(0))),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Insurance_booking', to='accounts.Booking')),
            ],
            options={
                'verbose_name': 'BaseModel',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='insurancedetails',
            name='handled_time',
        ),
        migrations.RemoveField(
            model_name='insurancedetails',
            name='hold_time',
        ),
        migrations.RemoveField(
            model_name='insurancedetails',
            name='insurance_state',
        ),
        migrations.RemoveField(
            model_name='insurancedetails',
            name='verification_date',
        ),
        migrations.AddField(
            model_name='insuranceverification',
            name='insurance_general',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_insurancedetails', to='accounts.InsuranceDetails'),
        ),
    ]
