# Generated by Django 2.1 on 2021-04-20 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0135_auto_20210420_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceverification',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='insuranceverification',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
