# Generated by Django 2.1 on 2021-04-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0136_auto_20210420_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceverification',
            name='hub_amount',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
    ]
