# Generated by Django 2.1 on 2021-05-06 05:18

from django.db import migrations, models
import django.db.models.deletion

dynamic_shift_variable = 'accounts.DynamicShiftManagement'

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0137_insuranceverification_hub_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='shift_dynamic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_booking', to=dynamic_shift_variable),
        ),
        migrations.AddField(
            model_name='doctorassigndaily',
            name='dynamic_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_doctorassign', to=dynamic_shift_variable),
        ),
        migrations.AddField(
            model_name='tempdoctorworkinfo',
            name='dynamicshift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_tempdoctorworkinfo', to=dynamic_shift_variable),
        ),
        migrations.AddField(
            model_name='user',
            name='dynamicshift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_user', to=dynamic_shift_variable),
        ),
    ]
