# Generated by Django 2.1 on 2021-05-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0138_auto_20210506_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
