# Generated by Django 2.1 on 2021-06-28 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0139_booking_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='destination_lat',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='destination_lng',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='has_insurance',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='ratingapp',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='shift_dynamic',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='source_lat',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='source_lng',
        ),
    ]
