# Generated by Django 2.1 on 2021-06-28 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('accounts', '0140_auto_20210628_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='temp_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_temp_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='insurancedetails',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='insurancedetails',
            name='profile_image',
            field=models.ManyToManyField(blank=True, to='images.AllImage'),
        ),
    ]
