# Generated by Django 2.1 on 2021-07-12 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0141_auto_20210628_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledBookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('visit_start_time', models.DateTimeField(blank=True, null=True)),
                ('visit_end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'BaseModel',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='covid_related',
            field=models.BooleanField(default=False, verbose_name='Covid related info'),
        ),
        migrations.AddField(
            model_name='cancelledbookings',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancelledbooking', to='accounts.Booking'),
        ),
        migrations.AddField(
            model_name='cancelledbookings',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancelledbooking_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cancelledbookings',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancelledbooking_hub', to='accounts.Hub'),
        ),
        migrations.AddField(
            model_name='cancelledbookings',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancelledbooking_room', to='accounts.Room'),
        ),
        migrations.AddField(
            model_name='cancelledbookings',
            name='van',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancelledbooking_van', to='accounts.Van'),
        ),
        migrations.AddField(
            model_name='cancelledbookings',
            name='virtualroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancelledbooking_virtualroom', to='accounts.VirtualRoom'),
        ),
    ]
