# Generated by Django 2.1 on 2021-07-12 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0142_auto_20210712_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelledbookings',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancelledbooking', to='accounts.Booking'),
        ),
    ]
